### ISSUE TITLE
Leaking file descriptors with Lua5.1 and LuaJIT

### ISSUE THREAD

**Issue by torhve** [daurnimator/lua-http#32] opened 2016-05-30 09:25 UTC
Working with lua-http in long runing processes leaves lsof with a lot of anon_inode that never gets cleaned.

See https://github.com/torhve/ivar2/blob/luahttp/test.lua#L134-L165 for way to reproduce

**Comment by daurnimator** [comment] 2016-05-30 09:34
To clarify: the test program seems to be leaking filedescriptors of the eventpoll and eventfd types.
This implies a cqueue object is leaking.

As a http2 connection is the only reachable place that cqueue objects get created dynamically from your code sample I assume that they are the ones leaking.

Furthermore, there are no leaked sockets; therefore I'm guessing the http2 connection object isn't being held onto.
This along with fact you're using lua5.1/luajit suggest that lua-http's http2 code doesn't follow cqueues limitations around ephemeron tables. From http://25thandclement.com/~william/projects/cqueues.pdf

> cqueues relies on ephemeron tables to prevent coroutine/controller reference cycles, and because Lua 5.1 does not support yielding from metamethods and iterators. LuaJIT removes the latter of these handicaps, and so cqueues targets LuaJIT secondarily. In lieu of ephemeron tables, application code must be sure not to hold a reference to a parent controller in an upvalue of the coroutine. Instead, use cqueues.running.

**Comment by daurnimator** [comment] 2016-05-30 16:05
I've confirmed that h2_connection leaks cqueues.
If you run the code:

```lua
require "http.h2_connection".new(require"cqueues.socket".pair(), "client")
collectgarbage()
collectgarbage()
```

You'll see that the fds are still open:

```$ ls -la /proc/14953/fd
total 0
dr-x------ 2 daurnimator daurnimator  0 May 31 01:26 .
dr-xr-xr-x 9 daurnimator daurnimator  0 May 31 01:26 ..
lrwx------ 1 daurnimator daurnimator 64 May 31 01:26 0 -> /dev/pts/3
lrwx------ 1 daurnimator daurnimator 64 May 31 01:26 1 -> /dev/pts/3
lrwx------ 1 daurnimator daurnimator 64 May 31 01:26 2 -> /dev/pts/3
lrwx------ 1 daurnimator daurnimator 64 May 31 01:26 3 -> 'socket:[2431281]'
lrwx------ 1 daurnimator daurnimator 64 May 31 01:26 5 -> 'anon_inode:[eventpoll]'
lrwx------ 1 daurnimator daurnimator 64 May 31 01:26 6 -> 'anon_inode:[eventfd]'
```

**Comment by daurnimator** [comment] 2016-06-03 02:47
Fixed in cqueues HEAD.

**Closed** 2016-08-20 14:42 UTC
Labels: bug
