### ISSUE TITLE
starttls: Invalid argument

### ISSUE THREAD

**Issue by satom99** [daurnimator/lua-http#73] opened 2017-02-27 19:41 UTC
```lua
local ws = require('http.websocket')
local socket = ws.new_from_uri('wss://gateway.discord.gg')
print( socket:connect(15) )
-- nil     starttls: Invalid argument      22
```
After a fresh Lua and luarocks installation this error occurs. Probably has to do with _cqueues_ but posting here just in case.

EDIT: Seems to work fine on Ubuntu, this error is proven to fire on Debian.

Also, after installing using luarocks, the module is eventually named after _http_0_1_0-http_ and not _http_ as expected.

**Comment by daurnimator** [comment] 2017-02-27 23:41
> After a fresh Lua and luarocks installation this error occurs. 

Could you show me output of `luarocks show http`?
Can you confirm that is the local copy in use? (e.g. run `strace -e open lua -l http.websocket < /dev/null |& grep websocket.lua`)

> `starttls: Invalid argument`

Do you any "Invalid argument" errors if you connect to a non-wss websocket?
e.g. try with ws://echo.websocket.org

> EDIT: Seems to work fine on Ubuntu, this error is proven to fire on Debian.

FWIW it works fine for me locally

> Also, after installing using luarocks, the module is eventually named after http_0_1_0-http and not http as expected.

I notice luarocks will do that if a 'http' module already exists (e.g. if you've installed via apt/dpkg). @hisham ping?

**Comment by daurnimator** [comment] 2017-02-28 14:45
> When connecting to ws://echo.websocket.org, the following is printed:
> 
>     nil flush: Invalid argument 22

That's good to know: the issue isn't in TLS negotiation.

Could you run it again with the environmental variable SOCKET_DEBUG=1 set?
e.g. `SOCKET_DEBUG=1 lua myscript.lua`

**Comment by satom99** [comment] 2017-02-28 14:51
> SOCKET_DEBUG=1 lua myscript.lua

Getting the following, before `nil flush` is printed;

`write([unknown]): Invalid argument`

**Comment by daurnimator** [comment] 2017-02-28 14:52
interesting.... Can you run under `strace`?

**Comment by satom99** [comment] 2017-02-28 14:59
Added it to the same [gist](https://gist.github.com/satom99/aea86be3fc5c2142074c271150ed90f3#file-strace-lua5-3-test-lua). Reading through, looks like some files aren't found.

**Comment by daurnimator** [comment] 2017-02-28 15:04
https://gist.github.com/satom99/aea86be3fc5c2142074c271150ed90f3#file-strace-lua5-3-test-lua-L860
> `connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("62.210.16.6")}, 16) = -1 EINVAL (Invalid argument)`

^^ That's where the error is coming from.

Looking [up higher](https://gist.github.com/satom99/aea86be3fc5c2142074c271150ed90f3#file-strace-lua5-3-test-lua-L834), I see that the same fd was previously used for another request:
> socket(PF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 3
> bind(3, {sa_family=AF_INET, sin_port=htons(57997), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
> connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.1")}, 16) = 0

I wonder if your OS doesn't like connect() on the same UDP socket more than once?
Could you provide your versions of debian, linux and glibc?

@wahern ping

**Comment by satom99** [comment] 2017-02-28 15:09
> cat /etc/*release
`PRETTY_NAME="Debian GNU/Linux 8 (jessie)"`

> cat /proc/version
`Linux version 4.4.35-1-pve (root@elsa) (gcc version 4.9.2 (Debian 4.9.2-10) )`

> ldd --version
`ldd (Debian GLIBC 2.19-18+deb8u7) 2.19`

**Comment by daurnimator** [comment] 2017-02-28 15:13
Oh, I just noticed the 
> ```
> recvfrom(3, 0x101ba8c, 768, 0, 0, 0) = -1 ECONNREFUSED (Connection refused)
> ```

Which is related to https://github.com/wahern/cqueues/pull/167.
That might not be the cause of the issue though.

**Comment by daurnimator** [comment] 2017-03-06 07:43
as far as I can tell, this a bug in cqueue's behaviour (or infact, [dns.c](https://github.com/wahern/dns)) and should be followed up there.

I *think* this is due to your /etc/resolv.conf containing a local resolver (e.g. 127.0.0.1) followed by *another* (working) server, and that your local dns resolver is not running.
A workaround would be to remove the local resolver from /etc/resolv.conf, or to make sure it's running.

**Comment by daurnimator** [comment] 2018-06-16 19:44
Closing as bug has been reported to cqueues/dns.c

**Closed by daurnimator** 2018-06-16 19:44 UTC
