### ISSUE TITLE
Any requests fails with "Address family not supported by protocol"

### ISSUE THREAD

**Issue by edubart** [daurnimator/lua-http#77] opened 2017-06-08 11:49 UTC
All my requests fails with the error `flush: Address family not supported by protocol`

My test case (the example provided in the docs):
```lua
local http_request = require "http.request"
local headers, stream = assert(http_request.new_from_uri("http://example.com"):go())
```

I get the following error:
```
$ luajit test.lua 
luajit: test.lua:2: flush: Address family not supported by protocol
stack traceback:
	[C]: in function 'assert'
	lala.lua:2: in main chunk
	[C]: at 0x00405b50
```

Note: I suspect this may be ralated to IPv6, my IPv6 is disabled in the kernel. My OS is ArchLinux.

**Comment by edubart** [comment] 2017-06-08 11:57
Should be something else, enabling IPv6 again in the kernel doesn't help.

**Comment by daurnimator** [comment] 2017-06-08 13:01
Can you run under `strace` and paste the output?

**Comment by edubart** [comment] 2017-06-08 13:20
strace output:

```
socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 3
getpid()                                = 17531
bind(3, {sa_family=AF_INET, sin_port=htons(7741), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
getpid()                                = 17531
getpid()                                = 17531
getpid()                                = 17531
getpid()                                = 17531
getpid()                                = 17531
getpid()                                = 17531
getpid()                                = 17531
getpid()                                = 17531
connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
sendto(3, "\0214\1\0\0\1\0\0\0\0\0\0\7example\3com\0\0\1\0\1", 29, 0, NULL, 0) = 29
recvfrom(3, 0x12443bc, 768, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
rt_sigpending([], 8)                    = 0
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
recvfrom(3, "\0214\201\200\0\1\0\1\0\0\0\0\7example\3com\0\0\1\0\1\300\f\0"..., 768, 0, NULL, NULL) = 45
socket(AF_UNSPEC, SOCK_STREAM|SOCK_CLOEXEC, 0) = -1 EAFNOSUPPORT (Address family not supported by protocol)
getpid()                                = 17531
getpid()                                = 17531
getpid()                                = 17531
getpid()                                = 17531
connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
sendto(3, "&\322\1\0\0\1\0\0\0\0\0\0\7example\3com\0\0\34\0\1", 29, 0, NULL, 0) = 29
recvfrom(3, "&\322\201\200\0\1\0\1\0\0\0\0\7example\3com\0\0\34\0\1\300\f\0"..., 768, 0, NULL, NULL) = 57
socket(AF_UNSPEC, SOCK_STREAM|SOCK_CLOEXEC, 0) = -1 EAFNOSUPPORT (Address family not supported by protocol)
rt_sigtimedwait([PIPE], NULL, {tv_sec=0, tv_nsec=0}, 8) = -1 EAGAIN (Resource temporarily unavailable)
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigpending([], 8)                    = 0
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
rt_sigtimedwait([PIPE], NULL, {tv_sec=0, tv_nsec=0}, 8) = -1 EAGAIN (Resource temporarily unavailable)
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigpending([], 8)                    = 0
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
rt_sigtimedwait([PIPE], NULL, {tv_sec=0, tv_nsec=0}, 8) = -1 EAGAIN (Resource temporarily unavailable)
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
epoll_create1(EPOLL_CLOEXEC)            = 4
eventfd2(0, EFD_CLOEXEC|EFD_NONBLOCK)   = 5
epoll_ctl(4, EPOLL_CTL_ADD, 5, {EPOLLIN, {u32=1087235624, u64=1087235624}}) = 0
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
epoll_wait(4, [{EPOLLIN, {u32=1087235624, u64=1087235624}}], 32, 0) = 1
read(5, "\1\0\0\0\0\0\0\0", 8)          = 8
epoll_wait(4, [], 32, 0)                = 0
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
epoll_wait(4, [{EPOLLIN, {u32=1087235624, u64=1087235624}}], 32, 0) = 1
read(5, "\1\0\0\0\0\0\0\0", 8)          = 8
epoll_wait(4, [], 32, 0)                = 0
close(3)                                = 0
rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[INT], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fd5f52e06f0}, {sa_handler=0x404550, sa_mask=[INT], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fd5f52e06f0}, 8) = 0
write(2, "luajit", 6luajit)                   = 6
write(2, ":", 1:)                        = 1
write(2, " ", 1 )                        = 1
write(2, "./test.lua:2: flush: Address fam"..., 154./test.lua:2: flush: Address family not supported by protocol
stack traceback:
	[C]: in function 'assert'
	./test.lua:2: in main chunk
	[C]: at 0x00405b50) = 154
```

**Comment by edubart** [comment] 2017-06-08 13:51
The problem is in cqueues, I've created another issue there. 
https://github.com/wahern/cqueues/issues/186

The code line `socket(AF_UNSPEC, SOCK_STREAM|SOCK_CLOEXEC, 0)` does not work in my system.

```
#include <sys/socket.h>
#include <stdio.h>
#include <string.h>

int main() {
    printf("%d", socket(AF_UNSPEC, SOCK_STREAM|SOCK_CLOEXEC, 0));
    perror("socket error");
    return 0;
}
```

```
$ gcc lala.c -o lala && ./lala
socket error: Address family not supported by protocol
```

**Comment by edubart** [comment] 2017-06-08 22:12
I wan't to give a try to this library, but this is blocking me from using it.

**Comment by daurnimator** [comment] 2017-06-09 01:45
> Note: I suspect this may be ralated to IPv6, my IPv6 is disabled in the kernel. My OS is ArchLinux.

How did you disable it? I tried replicating with `sysctl -w net.ipv6.conf.all.disable_ipv6=1` but was unsuccessful. Possibly your DNS server is returning AAAA records before A records?

**Comment by daurnimator** [comment] 2017-06-09 02:24
> Note: I suspect this may be ralated to IPv6, my IPv6 is disabled in the kernel. My OS is ArchLinux.

How did you disable it? I tried replicating with `sysctl -w net.ipv6.conf.all.disable_ipv6=1` but was unsuccessful. Possibly your DNS server is returning AAAA records before A records?

**Comment by edubart** [comment] 2017-06-09 10:27
I had `ipv6.disable=1`, chaging to `ipv6.disable=0` didn't help, my `eth0` interface does have an IPv6 address. My DNS was resolving AAAA records before A records, however I fixed that by adding `precedence ::ffff:0:0/96  100` in `/etc/gai.conf` (which is a file configuration for `getaddrinfo(3)`) and now `host www.google.com` does resolve A before AAAA records.

Maybe this can be related to newer kernel or GLIBC, my OS is ArchLinux which is a rolling release system, my kernel is 4.11.3 and GLIBC 2.25

**Comment by daurnimator** [comment] 2017-06-18 12:44
Closing here now that it's firmly established that the issue is inside of cqueues (and unrelated to ipv6 being turned off).

I wrote a possible fix in https://github.com/wahern/cqueues/issues/187

**Closed by daurnimator** 2017-06-18 12:44 UTC
